services:
  - type: web
    name: hilton-frontend
    env: static
    buildCommand: cd realestate_frontend && npm install && npm run build
    staticPublishPath: realestate_frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
